spring:
  datasource:
    url: jdbc:mysql://192.168.122.128:3306/demo
    driver-class-name: com.mysql.jdbc.Driver
    username: unimas
    password: unimas

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  redis:
    host: 192.168.122.128
    port: 6379